### ISSUE TITLE
ENH - Product Creation (Automatic Provisioning) 

### ISSUE THREAD

**Issue by app-generator** [app-generator/django-soft-ui-dashboard-stripe#2]
In order to speed up the local provisioning, would be nice to have the possibility to pull product information in the new product page. 

The KEY information, in this case, should be `Stripe Product ID` and the pull will provide: 

- general product information (title description . etc)
- Default image
- Default price

If doable, the same thing might be useful in the edit popUp. 

Please take a look. Ty! 

![image](https://user-images.githubusercontent.com/51070104/193775677-22491155-2cde-405a-b1ce-66c3b76fdda4.png)

**Comment by Mortrest** [comment]
Hello
OK. I will do it.
We can add another feature. Webhook give us power of adding product at product creation time on stripe dashboard. What is your opinion about this?

**Comment by app-generator** [comment]
This might be a nice solution. 
In case the user doesn't need the product in the app, he has the possibility to delete or update it. 

P.S. Please update the docs with this use case

Ty @Mortrest

**Comment by Mortrest** [comment]
Should I do both solutions or webhook solution only?

**Comment by app-generator** [comment]
Both please, just to provide more options to the user. 
I will push a small bonus for this effort. 
Ty guys!

🚀🚀

**Comment by app-generator** [comment]
P.S. please use the image from the default Image from Stripe. 
If the product is manually created, use a dummy one (as it is now). 

Ty @Mortrest

**Comment by app-generator** [comment]
The feature is validated. Ty @Mortrest
